### ISSUE TITLE
Is it possible to add an on tap gesture block into this lib?

### ISSUE THREAD

**Issue by alanfeng99** [miscavage/Alert#1]
Hi Sir,

As title, I tried to add it in but failed, the alert UIView didn't be able to response to on tap gesture event, I don't know why.

Maybe it's not the kind of alert / notification behaviour you think this lib should have, but please consider it as an option of enhancement. 

(I'm currently using JCNotificationBannerPresenter, but it's not as elegant as this lib and I'm thinking of changing it.)

Thanks!

**Comment by miscavage** [comment]
I am actually in the process of adding that in right now.
Adding in tap gestures and buttons.

**Comment by alanfeng99** [comment]
Looking forward to your update!  

I wonder why I can't get the gesture to work, I guess I will find out once you release the updates. :D
